let NewProducts = 
    [
        {
         "name": "SCULPFUN 30L/Min 200-240V Air Pump Compressor for Laser Engraver",
         "description": "SCULPFUN 30L/Min 200-240V Air Pump Compressor for Laser Engraver, Adjustable Speed Low Noise Low Vibration - EU Plug",
         "price": "$115.95",
         "ratings": "121",
         "imgURL": "https://img.gkbcdn.com/p/2022-05-30/SCULPFUN-30L-Min-Air-Pump-Compressor-EU-Plug-501434-0._w280_.jpg",
         "whislist": "12",
         "arrived":"7",
         "sale":"yes",
         "shipping":"no",
         "country":"Europe"
         
        },
        {
         "name": "Creality Smart Kit 2.0 Wifi Box",
         "description": "Creality Smart Kit 2.0 Wifi Box, Cloud Slice, Cloud Printing, WiFi Box , 1080P Web Camera, Remote Control",
         "price": "$86.96",
         "cutprice": "$94.87",
         "off": "(8% off)",
         "ratings": "110",
         "imgURL": "https://img.gkbcdn.com/p/2022-06-07/Creality-Smart-Kit-2-0-with-8G-TF-Card-501574-0._w280_.jpg",
         "whislist": "4",
         "arrived":"15",
         "sale":"no",
         "shipping":"yes",
         "country":"Poland"
        },
        {
         "name": "Mini Wireless Camera Real 1080P Wifi Camera",
         "description": "Mini Wireless Camera Real 1080P Wifi Camera Home Nanny Tiny Cam Baby with Night Vision Motion Cell Phone App Detection - Black",
         "price": "$19.75",
         "ratings": "99",
         "imgURL": "https://img.gkbcdn.com/p/2022-05-27/a69f6f8df4584396aa09a7e4626d9f79-501364-0._w280_.jpg",
         "whislist": "9",
         "arrived":"30",
         "sale":"yes",
         "shipping":"no",
         "country":"Germany"
        },
        {
         "name": "Tronsmart T7 Mini 15W TWS Bluetooth Speaker",
         "description": "Tronsmart T7 Mini 15W TWS Bluetooth Speaker, Balanced Bass, IPX7 Waterproof, LED Modes",
         "price": "$35.57",
         "cutprice": "$52.70",
         "off": "(33% off)",
         "ratings": "89",
         "imgURL": "https://img.gkbcdn.com/p/2022-06-07/tronsmart-t7-mini-15w-bluetooth-speaker-ec260e-1654581513598._w280_.jpg",
         "whislist": "14",
         "arrived":"7",
         "sale":"no",
         "shipping":"yes",
         "country":"Spain"
        },
        {
         "name": "Q9 Pro GT2 Smartwatch 1.85'' TFT HD Touch Screen",
         "description": "Q9 Pro GT2 Smartwatch 1.85'' TFT HD Touch Screen BT5.0 Heart Rate Blood Pressure SpO2 Monitor Fitness Tracker - Black&Gold",
         "price": "$31.60",
         "ratings": "78",
         "imgURL": "https://img.gkbcdn.com/p/2022-05-25/Q9-Pro-GT2-Smartwatch-1-85---TFT-HD-Touch-Screen-BT5-0-Black-Gold-501264-0._w280_.jpg",
         "whislist": "4",
         "arrived":"15",
         "sale":"yes",
         "shipping":"no",
         "country":"United_States"
        },
        {
         "name": "360 Degree Rotatable 1080p HD Camera",
         "description": "360 Degree Rotatable 1080p HD Camera, WiFi Wireless Smart Night Vision Camera, 2-way Voice AP Connection - EU Plug",
         "price": "$25.03",
         "ratings": "67",
         "imgURL": "https://img.gkbcdn.com/p/2022-06-01/360-Degree-Rotatable-1080p-HD-Camera-EU-Plug-501469-0._w280_.jpg",
         "whislist": "3",
         "arrived":"30",
         "sale":"no",
         "shipping":"yes",
         "country":"United_Kingdom"
        },
        {
         "name": "3.5 Inch IPS TYPE-C Secondary Screen CPU",
         "description": "3.5 Inch IPS TYPE-C Secondary Screen CPU GPU RAM HDD Monitoring USB Display",
         "price": "$48.75",
         "ratings": "120",
         "imgURL": "https://img.gkbcdn.com/p/2022-05-30/3-5-Inch-IPS-TYPE-C-Secondary-Screen-CPU-GPU-RAM-HDD-Monitoring-501430-0._w280_.jpg",
         "whislist": "5",
         "arrived":"7",
         "sale":"yes",
         "shipping":"no",
         "country":"Netherland"
        },
        {
         "name": "ORTUR Laser Engraving Y-axis Rotary Roller",
         "description": "ORTUR Laser Engraving Y-axis Rotary Roller Ortur-YRR Laser Master Part to Engrave on Cans, Eggs, Cylinders",
         "price": "$105.41",
         "ratings": "131",
         "imgURL": "https://img.gkbcdn.com/p/2022-05-30/ortur-laser-engraving-y-axis-rotary-roller-c8a0c4-1653875208088._w280_.jpg",
         "whislist": "5",
         "arrived":"15",
         "sale":"no",
         "shipping":"yes",
         "country":"China"
        },
        {
         "name": "Haylou RS4 Plus Smartwatch 1.78-Inch Retina AMOLED",
         "description": "Haylou RS4 Plus Smartwatch 1.78-Inch Retina AMOLED HD Display 105 Sports Mode SpO2 Heart Rate - Black Silver",
         "price": "$79.05",
         "cutprice": "$90.92",
         "off": "(13% off)",
         "ratings": "142",
         "imgURL": "https://img.gkbcdn.com/p/2022-05-25/Haylou-RS4-Plus-Smartwatch-1-78-Inch-Retina-AMOLED-HD-Display-Sliver-501267-0._w280_.jpg",
         "whislist": "4",
         "arrived":"30",
         "sale":"yes",
         "shipping":"no",
         "country":"Europe"
        },
        {
         "name": "Ortur LU2-10A 10W Laser Module",
         "description": "Ortur LU2-10A 10W Laser Module, 0.07*0.06mm Compressed Spot, Fixed Focus, Air Assist Interface, For Aufero and Other Desktop Laser Engravers",
         "price": "$355.79",
         "ratings": "153",
         "imgURL": "https://img.gkbcdn.com/p/2022-05-28/Ortur-Laser-Module-LU2-10A-24V-10W-501387-2._w280_.jpg",
         "whislist": "1",
         "arrived":"7",
         "sale":"no",
         "shipping":"yes",
         "country":"Poland"
        },
        {
         "name": "Metal Tube Spare Part for JIMMY JV51 Vacuum Cleaner",
         "description": "Metal Tube Spare Part for JIMMY JV51 Vacuum Cleaner",
         "price": "$56.65",
         "ratings": "164",
         "imgURL": "https://img.gkbcdn.com/p/2022-06-07/Metal-Tube-Spare-Part-for-JIMMY-JV51-Vacuum-Cleaner-501612-0._w280_.jpg",
         "whislist": "0",
         "arrived":"15",
         "sale":"yes",
         "shipping":"no",
         "country":"Germany"
        },
        {
         "name": "Mibro A1 Smartwatch 1.28'' HD Touch Screen",
         "description": "Mibro A1 Smartwatch 1.28'' HD Touch Screen BT5.0 Heart Rate SpO2 Sensor, 20 Sports Modes, 5ATM Waterproof - Black",
         "price": "$52.69",
         "ratings": "175",
         "imgURL": "https://img.gkbcdn.com/p/2022-05-25/Mibro-A1-Smartwatch-1-28---HD-Touch-Screen-BT5-0-Black-501275-0._w280_.jpg",
         "whislist": "5",
         "arrived":"30",
         "sale":"no",
         "shipping":"yes",
         "country":"Spain"
        },
        {
         "name": "Hawkeye Firefly Q7 120 Degree Wide Angle 1080P 30FPS HD Mini WiFi",
         "description": "Hawkeye Firefly Q7 120 Degree Wide Angle 1080P 30FPS HD Mini WiFi FPV Action Sport Camera Aerial Camcorder - Black",
         "price": "$73.78",
         "cutprice": "$88.28",
         "off": "(16% off)",
         "ratings": "186",
         "imgURL": "https://img.gkbcdn.com/p/2022-05-25/Hawkeye-Firefly-Q7-120-Degree-Wide-Angle-Action-Sport-Camera-Black-501307-0._w280_.jpg",
         "whislist": "4",
         "arrived":"7",
         "sale":"yes",
         "shipping":"no",
         "country":"United_States"
        },
        {
         "name": "3PCS Dust Bag for Roborock",
         "description": "3PCS Dust Bag for Roborock Q7 MAX+/S7 MAXV Ultra Automatic Suction Station",
         "price": "$19.75",
         "ratings": "198",
         "imgURL": "https://img.gkbcdn.com/p/2022-05-30/Roborock-Q7-MAX--S7-MAXV-Ul-automatic-suction-station-Dust-Bag---3-Pcs-501433-0._w280_.jpg",
         "whislist": "3",
         "arrived":"15",
         "sale":"no",
         "shipping":"yes",
         "country":"United_Kingdom"
        },
        {
         "name": "LOKMAT APPLLP 5 Smartwatch 4G WiFi LTE Watch",
         "description": "LOKMAT APPLLP 5 Smartwatch 4G WiFi LTE Watch with Dual Cameras 1.6'' TFT Screen RAM 4GB ROM 128GB for Android and iOS",
         "price": "$312.29",
         "ratings": "212",
         "imgURL": "https://img.gkbcdn.com/p/2022-05-25/LOKMAT-APPLLP-5-Smartwatch-4G-WiFi-LTE-Watch-with-Dual-Cameras-501274-0._w280_.jpg",
         "whislist": "3",
         "arrived":"30",
         "sale":"yes",
         "shipping":"no",
         "country":"Netherland"
        },
        {
         "name": "LEMFO LF31 Smartwatch BT Calling Watch",
         "description": "LEMFO LF31 Smartwatch BT Calling Watch 1.32'' Touch Screen, HR, SpO2, BP Monitor, NFC for Android iOS - Black Steel",
         "price": "$57.96",
         "ratings": "23",
         "imgURL": "https://img.gkbcdn.com/p/2022-05-25/LEMFO-LF31-Smartwatch-BT-Calling-Watch-Black-Steel-501273-0._w280_.jpg",
         "whislist": "3",
         "arrived":"7",
         "sale":"no",
         "shipping":"yes",
         "country":"China"
        },
        {
         "name": "Haylou LS09A Smartwatch 1.28-Inch TFT Display",
         "description": "Haylou LS09A Smartwatch 1.28-Inch TFT Display BT5.1 SpO2 Heart Rate,Sleep Monitor 12 Sports Modes",
         "price": "$52.70",
         "ratings": "98",
         "imgURL": "https://img.gkbcdn.com/p/2022-05-25/Haylou-LS09A-Smartwatch-1-28-Inch-TFT-Display-BT5-1-501269-0._w280_.jpg",
         "whislist": "3",
         "arrived":"15",
         "sale":"yes",
         "shipping":"no",
         "country":"Poland"
        },
        {
         "name": "Haylou RS3 LS04 Smartwatch 1.2-Inch AMOLED HD Display",
         "description": "Haylou RS3 LS04 Smartwatch 1.2-Inch AMOLED HD Display BT5.0 GPS Fitness Tracker 14 Workout Modes",
         "price": "$94.86",
         "ratings": "45",
         "imgURL": "https://img.gkbcdn.com/p/2022-05-25/Haylou-RS3-LS04-Smartwatch-1-2-Inch-AMOLED-HD-Display-501268-0._w280_.jpg",
         "whislist": "3",
         "arrived":"30",
         "sale":"yes",
         "shipping":"no",
         "country":"Europe"
        },
        {
         "name": "Raspberry Pi 4 Model B 8GB RAM ",
         "description": "Raspberry Pi 4 Model B 8GB RAM BCM2711 Quad Core Cortex-A72 ARM v8 1.5GHz Support 2.4/5.0 GHz WiFi Bluetooth 5.0 - 8GB",
         "price": "$365.02",
         "ratings": "56",
         "imgURL": "https://img.gkbcdn.com/p/2022-05-28/Raspberry-Pi-4-Model-B-8GB-RAM-BCM2711-Quad-Core-501375-0._w280_.jpg",
         "whislist": "2",
         "arrived":"7",
         "sale":"no",
         "shipping":"yes",
         "country":"Germany"
        },
        {
         "name": "Hubsan Mini GPS 6KM FPV with 1/1.3 CMOS 4K 30fps Camera",
         "description": "Hubsan Mini GPS 6KM FPV with 1/1.3 CMOS 4K 30fps Camera 3-axis Gimbal 45mins Flight Time with Storage Bag - 2 Batteries",
         "price": "$790.67",
         "cutprice": "$932.99",
         "off": "(15% off)",
         "ratings": "87",
         "imgURL": "https://img.gkbcdn.com/p/2022-05-25/Hubsan-MiNi-GPS-6KM-FPV-with-1-1-3-CMOS-4K-30fps-Camera-2-Batteries-501278-0._w280_.jpg",
         "whislist": "3",
         "arrived":"15",
         "sale":"yes",
         "shipping":"no",
         "country":"Spain"
        },
        {
         "name": "XNANO X1 Android 9.0 LCD Projector, 1080P Native Output",
         "description": "XNANO X1 Android 9.0 LCD Projector, 1080P Native Output, 12000LM, Dolby Audio, AC WiFi Bluetooth, HDR 10+, Keystone Correction, 8K Decoding, 2GB/16GB, EU Plug",
         "price": "$263.55",
         "ratings": "299",
         "imgURL": "https://img.gkbcdn.com/p/2022-06-09/XNANO-X1-Android-9-0-LCD-Projector-8K-4K-Dolby-460ANSI--5G-WIFI-501672-0._w280_.jpg",
         "whislist": "3",
         "arrived":"30",
         "sale":"no",
         "shipping":"yes",
         "country":"United_States"
        },
        {
         "name": "8Bitdo USB Wireless Adapter Bluetooth",
         "description": "8Bitdo USB Wireless Adapter Bluetooth 4.0 Compatible with Switch, Windows, Mac OS, Raspberry Pi",
         "price": "$22.39",
         "ratings": "234",
         "imgURL": "https://img.gkbcdn.com/p/2022-06-06/8BitDo-USB-Wireless-Adapter-2-501568-0._w280_.jpg",
         "whislist": "2",
         "arrived":"7",
         "sale":"yes",
         "shipping":"no",
         "country":"United_Kingdom"
        },
        {
         "name": "WLtoys 104002 1/10 2.4G 4WD RC Car Off-road Brushless Motor",
         "description": "WLtoys 104002 1/10 2.4G 4WD RC Car Off-road Brushless Motor Max Speed 60km/h - Three Batteries",
         "price": "$316.26",
         "ratings": "63",
         "imgURL": "https://img.gkbcdn.com/p/2022-05-26/WLtoys-104002-1-10-2-4G-4WD-RC-Car-Off-road-Three-Batteries-501345-0._w280_.jpg",
         "whislist": "1",
         "arrived":"15",
         "sale":"no",
         "shipping":"yes",
         "country":"Netherland"
        },
        {
         "name": "WLtoys WL916 High Speed 2.4G RC Boat Brushless Motor",
         "description": "WLtoys WL916 High Speed 2.4G RC Boat Brushless Motor Racing Boat 60km/h Ship Toys for Kids Black - Three Batteries",
         "price": "$197.66",
         "ratings": "72",
         "imgURL": "https://img.gkbcdn.com/p/2022-05-25/WLtoys-WL916-High-Speed-2-4G-RC-Boat-Three-Batteries-501311-0._w280_.jpg",
         "whislist": "1",
         "arrived":"30",
         "sale":"yes",
         "shipping":"no",
         "country":"China"
        },
        {
            "name": "FIFISH V6 EXPERT Robotic Arms for Underwater Drone",
            "description": "FIFISH V6 EXPERT Robotic Arms for Underwater Drone Multiple Ports to Connect Underwater Observation Navigation Tools",
            "price": "$817.02",
            "cutprice": "$1035.78",
            "off": "(21% off)",
            "ratings": "89",
            "imgURL": "https://img.gkbcdn.com/p/2022-06-13/FIFISH-V6-EXPERT-Underwater-ROV-with-Robotic-Arms-Multiple-Ports-502684-0._w280_.jpg",
            "whislist": "0",
            "arrived":"7",
            "sale":"no",
            "shipping":"yes",
            "country":"Poland"
           },
           {
            "name": "JJRC H105 2.4G RC Drone with Camera Airbornes",
            "description": "JJRC H105 2.4G RC Drone with Camera Airborne Gyro Rotation Quadcopter RTF 3 Advanced Training Mode for Beginner - Blue 2 Batteries",
            "price": "$55.33",
            "ratings": "33",
            "imgURL": "https://img.gkbcdn.com/p/2022-06-13/JJRC-H105-2-4G-RC-Drone-Blue-2-Batteries-502658-0._w280_.jpg",
            "whislist": "0",
            "arrived":"15",
            "sale":"yes",
            "shipping":"no",
            "country":"Europe"
           },
           {
            "name": "A2 Indoor Security Camera, Baby Monitor Smart Home",
            "description": "A2 Indoor Security Camera, Baby Monitor Smart Home IP Wi-Fi Camera with Night Vision/2.4GHZ/Motion Detection/2-Way Voice",
            "price": "$18.44",
            "ratings": "45",
            "imgURL": "https://img.gkbcdn.com/p/2022-06-11/A2-Indoor-Security-Camera-502645-0._w280_.jpg",
            "whislist": "0",
            "arrived":"30",
            "sale":"no",
            "shipping":"yes",
            "country":"Germany"
           },
           {
            "name": "Nextool 12 In 1 900lm Music Pulse Lamp",
            "description": "Nextool 12 In 1 900lm Music Pulse Lamp, Telescopic Focus, 245M Long Range LED Flashlight Torch, Mini Speaker Power Bank",
            "price": "$56.65",
            "cutprice": "$63.24",
            "off": "(10% off)",
            "ratings": "55",
            "imgURL": "https://img.gkbcdn.com/p/2022-06-11/Nextool-12-In-1-900lm-Music-Pulse-Lamp-502644-0._w280_.jpg",
            "whislist": "0",
            "arrived":"7",
            "sale":"yes",
            "shipping":"no",
            "country":"Spain"
           },
           {
            "name": "JJRC Q102 1/14 2.4G Racing RC Car",
            "description": "JJRC Q102 1/14 2.4G Racing RC Car 20km/h Max Speed 25 Mins Using Time RC Toy - Red",
            "price": "$47.43",
            "ratings": "213",
            "imgURL": "https://img.gkbcdn.com/p/2022-06-11/JJRC-Q102-1-14-2-4G-Racing-RC-Car-Red-502455-0._w280_.jpg",
            "whislist": "0",
            "arrived":"15",
            "sale":"no",
            "shipping":"yes",
            "country":"United_States"
           },
           {
            "name": "Sabbat E18 TWS Earbuds Wireless Bluetooth",
            "description": "Sabbat E18 TWS Earbuds Wireless Bluetooth 5.2 Music and Gaming Earphone - Moonlight Silver",
            "price": "$104.09",
            "ratings": "155",
            "imgURL": "https://img.gkbcdn.com/p/2022-06-11/Sabbat-E18-TWS-Earbuds-Wireless-Bluetooth-5-2-Moonlight-Silver-502452-0._w280_.jpg",
            "whislist": "0",
            "arrived":"30",
            "sale":"yes",
            "shipping":"no",
            "country":"United_States"
           },
           {
            "name": "JJRC X22 GPS 5G WiFi FPV 6K ESC Camera",
            "description": "JJRC X22 GPS 5G WiFi FPV 6K ESC Camera 3-Axis Gimbal Brushless RC Drone Obstacle Avoidance 33mins Flight Time - 3 Batteries",
            "price": "$421.68",
            "cutprice": "$474.39",
            "off": "(11% off)",
            "ratings": "176",
            "imgURL": "https://img.gkbcdn.com/p/2022-06-11/JJRC-X22-1080P-3-Axis-Gimbal-GPS-RC-Drone-Three-Batteries-502443-0._w280_.jpg",
            "whislist": "0",
            "arrived":"7",
            "sale":"no",
            "shipping":"yes",
            "country":"Netherland"
           },
           {
            "name": "S1 Smart Wireless Door Camera with Chime",
            "description": "S1 Smart Wireless Door Camera with Chime, Night Vision, 2.4GHz WiFi, 2-Way Audio, Call Receivers for iOS & Android",
            "price": "$21.07",
            "ratings": "59",
            "imgURL": "https://img.gkbcdn.com/p/2022-06-11/S1-Smart-Wireless-Door-Camera-with-Chime-502440-0._w280_.jpg",
            "whislist": "0",
            "arrived":"15",
            "sale":"yes",
            "shipping":"no",
            "country":"China"
           },
           {
            "name": "J2 Colorful Flame Diffuser with 3D Dynamic Mist",
            "description": "J2 Colorful Flame Diffuser with 3D Dynamic Mist, 250ml Ultrasonic for 12 Hours Working Time Auto-off Night Lamp Function",
            "price": "$39.52",
            "cutprice": "$52.70",
            "off": "(25% off)",
            "ratings": "249",
            "imgURL": "https://img.gkbcdn.com/p/2022-06-11/J2-Colorful-Flame-Diffuser-with-3D-Dynamic-Mist-502439-0._w280_.jpg",
            "whislist": "0",
            "arrived":"30",
            "sale":"no",
            "shipping":"yes",
            "country":"Poland"
           },
           {
            "name": "GREEN TIME T11 Multifunction Wireless Charging Bluetooth",
            "description": "GREEN TIME T11 Multifunction Wireless Charging Bluetooth 5.0 Speaker, Bedside Alarm Clock FM Radio Player - White",
            "price": "$60.61",
            "cutprice": "$72.47",
            "off": "(16% off)",
            "ratings": "149",
            "imgURL": "https://img.gkbcdn.com/p/2022-06-09/GREEN-TIME-T11-Wireless-Charging-Bluetooth-Speaker-501661-0._w280_.jpg",
            "whislist": "0",
            "arrived":"7",
            "sale":"yes",
            "shipping":"no",
            "country":"Europe"
           },
           {
            "name": "GREEN TIME K1 Pro Alarm Clock Radio",
            "description": "GREEN TIME K1 Pro Alarm Clock Radio, LCD Temperature Display, Electronic Digital Clock with USB Charging Port - White",
            "price": "$39.52",
            "cutprice": "$46.11",
            "off": "(14% off)",
            "ratings": "119",
            "imgURL": "https://img.gkbcdn.com/p/2022-06-08/GREEN-TIME-K1-Pro-Alarm-Clock-Radio-White-501648-0._w280_.jpg",
            "whislist": "0",
            "arrived":"15",
            "sale":"no",
            "shipping":"yes",
            "country":"Germany"
           },
           {
            "name": "GREEN TIME T2 Dual USB Charging Alarm Clock",
            "description": "GREEN TIME T2 Dual USB Charging Alarm Clock Wireless Radio, LCD Screen Perpetual Calendar, Temperature Display - White",
            "price": "$39.52",
            "cutprice": "$43.47",
            "off": "(9% off)",
            "ratings": "59",
            "imgURL": "https://img.gkbcdn.com/p/2022-06-08/GREEN-TIME-T2-Alarm-Clock-Radio-White-501646-0._w280_.jpg",
            "whislist": "0",
            "arrived":"30",
            "sale":"yes",
            "shipping":"no",
            "country":"Spain"
           },
           {
            "name": "GREEN TIME M9 Electronic Alarm Clock Speaker",
            "description": "GREEN TIME M9 Electronic Alarm Clock Speaker, Multifunctional Bedside Radio, Desktop Charging Bluetooth Audio - EU Plug",
            "price": "$47.43",
            "cutprice": "$51.38",
            "off": "(8% off)",
            "ratings": "69",
            "imgURL": "https://img.gkbcdn.com/p/2022-06-08/GREEN-TIME-M9-Electronic-Alarm-Clock-Speaker-EU-Plug-501644-0._w280_.jpg",
            "whislist": "0",
            "arrived":"7",
            "sale":"no",
            "shipping":"yes",
            "country":"United_States"
           },
           {
            "name": "GREEN TIME X7 Wireless Fast Charger Alarm Clock Radio",
            "description": "GREEN TIME X7 Wireless Fast Charger Alarm Clock Radio, LED Smart Digital Desktop, Subwoofer Bluetooth Speaker - EU Plug",
            "price": "$56.65",
            "cutprice": "$65.88",
            "off": "(14% off)",
            "ratings": "79",
            "imgURL": "https://img.gkbcdn.com/p/2022-06-08/GREEN-TIME-X7-Bluetooth-Charger-Alarm-Clock-Radio-EU-Plug-501643-0._w280_.jpg",
            "whislist": "0",
            "arrived":"15",
            "sale":"yes",
            "shipping":"no",
            "country":"United_Kingdom"
           },
           {
            "name": "GREEN TIME M7-QI Bluetooth Alarm Clock Speaker",
            "description": "GREEN TIME M7-QI Bluetooth Alarm Clock Speaker, Mobile Phone Wireless Charging, U Disk TF Card Play, FM Radio - Black",
            "price": "$65.88",
            "cutprice": "$89.60",
            "off": "(26% off)",
            "ratings": "99",
            "imgURL": "https://img.gkbcdn.com/p/2022-06-08/GREEN-TIME-M7-QI-Bluetooth-Alarm-Clock-Speaker-Black-501618-0._w280_.jpg",
            "whislist": "0",
            "arrived":"30",
            "sale":"no",
            "shipping":"yes",
            "country":"Netherland"
           },
           {
            "name": "GREEN TIME X10 Bluetooth 5.0 Alarm Clock Speaker",
            "description": "GREEN TIME X10 Bluetooth 5.0 Alarm Clock Speaker Bedside Night Light, LED Display Computer Audio, FM Radio - Black",
            "price": "$43.47",
            "cutprice": "$51.38",
            "off": "(15% off)",
            "ratings": "89",
            "imgURL": "https://img.gkbcdn.com/p/2022-06-08/GREEN-TIME-X10-Bluetooth-Alarm-Clock-Speaker-Black-501614-0._w280_.jpg",
            "whislist": "0",
            "arrived":"15",
            "sale":"yes",
            "shipping":"no",
            "country":"China"
           }
]


localStorage.setItem("NewProducts",JSON.stringify(NewProducts))


let BestSeller = [
    {
        "name": "Zonestar Z9V5 MK3 3D Printer Auto Leveling Adjustable",
        "description": "Zonestar Z9V5 MK3 3D Printer Auto Leveling Adjustable 4 Extruder Design Mix-Color Printing Resume Printing",
        "price": "$764.31",
        "cutoff": "$952.76",
        "off": "(20% off)",
        "ratings": "18",
        "imgURL": "https://img.gkbcdn.com/p/2022-04-22/Zonestar-Z9V5-MK3-3D-Printer-499936-0._w280_.jpg",
        "wishlist": "5",
        "arrived":"7",
        "sale":"yes",
        "shipping":"no",
        "country":"Europe"
      },
      {
        "name": "FIIDO M1 Pro 12.8Ah 48V 500W 20 Inches Folding Moped Bicycle",
        "description": "FIIDO M1 Pro 12.8Ah 48V 500W 20 Inches Folding Moped Bicycle 40km/h Top Speed 130KM Mileage Range Electric Bike",
        "price": "$1647.24",
        "cutoff": "$1955.60",
        "off": "(16% off)",
        "ratings": "119",
        "imgURL": "https://img.gkbcdn.com/p/2022-04-09/FIIDO-M1-Pro-12-8Ah-48V-500W-499384-0._w280_.jpg",
        "wishlist": "7",
        "arrived":"15",
        "sale":"no",
        "shipping":"yes",
        "country":"Poland"
      },
      {
        "name": "FIIDO T1 Cargo Electric Bike 750W Power",
        "description": "FIIDO T1 Cargo Electric Bike 750W Power 50km/h Max Speed 48V 20AH Lithium Battery 150km Range Shock Absorber - Green",
        "price": "$2174.36",
        "cutoff": "$2577.60",
        "off": "(16% off)",
        "ratings": "78",
        "imgURL": "https://img.gkbcdn.com/p/2022-04-09/b195caaecd76491aac56e51460569c35-499383-0._w280_.jpg",
        "wishlist": "4",
        "arrived":"30",
        "sale":"yes",
        "shipping":"no",
        "country":"Germany"
      },
      {
        "name": "ERYONE Matte PLA Filament for 3D Printer",
        "description": "ERYONE Matte PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - Black",
        "price": "$52.70",
        "ratings": "25",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-17/ERYONE-Matte-PLA-Filament-for-3D-Printer-1-75mm-496660-0._w280_.jpg",
        "wishlist": "2",
        "arrived":"7",
        "sale":"no",
        "shipping":"yes",
        "country":"Spain"
      },
      {
        "name": "ERYONE Matte PLA Filament for 3D Printer",
        "description": "ERYONE Matte PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - White",
        "price": "$52.70",
        "ratings": "118",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-17/ERYONE-Matte-PLA-Filament-for-3D-Printer-496645-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"15",
        "sale":"yes",
        "shipping":"no",
        "country":"United_States"
      },
      {
        "name": "ERYONE Matte PLA Filament for 3D Printer",
        "description": "ERYONE Matte PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - Olive Green",
        "price": "$52.70",
        "ratings": "219",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-17/ERYONE-Matte-PLA-Filament-for-3D-Printer-496650-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"30",
        "sale":"no",
        "shipping":"yes",
        "country":"United_Kingdom"
      },
      {
        "name": "ERYONE Matte PLA Filament for 3D Printer",
        "description": "ERYONE Matte PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - Navy Blue",
        "price": "$52.70",
        "ratings": "217",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-17/ERYONE-Matte-PLA-Filament-for-3D-Printer-1-75mm-496655-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"7",
        "sale":"yes",
        "shipping":"no",
        "country":"Netherland"
      },
      {
        "name": "ERYONE Matte PLA Filament for 3D Printer",
        "description": "ERYONE Matte PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - Aqua Blue",
        "price": "$52.70",
        "ratings": "117",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-17/ERYONE-Matte-PLA-Filament-for-3D-Printer-496665-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"15",
        "sale":"no",
        "shipping":"yes",
        "country":"China"
      },
      {
        "name": "ERYONE Matte PLA Filament for 3D Printer",
        "description": "ERYONE Matte PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - Gray",
        "price": "$52.70",
        "ratings": "114",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-17/ERYONE-Matte-PLA-Filament-for-3D-Printer-496670-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"30",
        "sale":"yes",
        "shipping":"no",
        "country":"Europe"
      },
      {
        "name": "ERYONE Matte PLA Filament for 3D Printer",
        "description": "ERYONE Matte PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - Lilac Purple",
        "price": "$52.70",
        "ratings": "98",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-17/ERYONE-Matte-PLA-Filament-for-3D-Printer-1-75mm-496675-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"7",
        "sale":"no",
        "shipping":"yes",
        "country":"Poland"
      },
      {
        "name": "ERYONE Star One 3D Printer Auto-Leveling",
        "description": "ERYONE Star One 3D Printer Auto-Leveling, Super Quiet 3D Printer with TMC2208, 32Bit Motherboard FDM Forming Technology",
        "price": "$446.72",
        "ratings": "23",
        "imgURL": "https://img.gkbcdn.com/p/2022-05-27/ERYONE-Star-One-3D-Printer-501374-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"15",
        "sale":"yes",
        "shipping":"no",
        "country":"Germany"
      },
      {
        "name": "ERYONE M2 Filament Dryer Box for 3D Printer Filament",
        "description": "ERYONE M2 Filament Dryer Box for 3D Printer Filament, Filament Storage Holder, Spool Storage Box, Temperature Adjustment",
        "price": "$72.47",
        "ratings": "56",
        "imgURL": "https://img.gkbcdn.com/p/2022-06-03/ERYONE-M2-Filament-Dryer-Box-501494-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"30",
        "sale":"no",
        "shipping":"yes",
        "country":"Spain"
      },
      {
        "name": "ERYONE Silk PLA Filament for 3D Printer",
        "description": "ERYONE Silk PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - Bronze",
        "price": "$39.52",
        "cutoff": "$48.75",
        "off": "(19% off)",
        "ratings": "34",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-14/ERYONE-Silk-PLA-Filament-for-3D-Printer-1-75mm-496548-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"7",
        "sale":"yes",
        "shipping":"no",
        "country":"United_States"
      },
      {
        "name": "ERYONE Silk PLA Filament for 3D Printer",
        "description": "ERYONE Silk PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - Blue",
        "price": "$39.52",
        "cutoff": "$48.75",
        "off": "(19% off)",
        "ratings": "187",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-15/ERYONE-Silk-PLA-Filament-for-3D-Printer-1-75mm-496569-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"15",
        "sale":"no",
        "shipping":"yes",
        "country":"United_Kingdom"
      },
      {
        "name": "ERYONE Silk PLA Filament for 3D Printer",
        "description": "ERYONE Silk PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - Gold",
        "price": "$39.52",
        "cutoff": "$48.75",
        "off": "(19% off)",
        "ratings": "116",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-15/ERYONE-Silk-PLA-Filament-for-3D-Printer-1-75mm-496581-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"30",
        "sale":"yes",
        "shipping":"no",
        "country":"Netherland"
      },
      {
        "name": "ERYONE Silk PLA Filament for 3D Printer",
        "description": "ERYONE Silk PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - Red",
        "price": "$39.52",
        "cutoff": "$48.75",
        "off": "(19% off)",
        "ratings": "62",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-16/ERYONE-Silk-PLA-Filament-for-3D-Printer-496605-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"7",
        "sale":"no",
        "shipping":"yes",
        "country":"China"
      },
      {
        "name": "ERYONE Silk PLA Filament for 3D Printer",
        "description": "ERYONE Silk PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - Red Copper",
        "price": "$39.52",
        "cutoff": "$48.75",
        "off": "(19% off)",
        "ratings": "267",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-16/ERYONE-Silk-PLA-Filament-for-3D-Printer-496610-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"15",
        "sale":"yes",
        "shipping":"no",
        "country":"Europe"
      },
      {
        "name": "ERYONE Silk PLA Filament for 3D Printer",
        "description": "ERYONE Silk PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - Silver",
        "price": "$39.52",
        "cutoff": "$48.75",
        "off": "(19% off)",
        "ratings": "69",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-16/ERYONE-Silk-PLA-Filament-for-3D-Printer-496620-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"30",
        "sale":"no",
        "shipping":"yes",
        "country":"Poland"
      },
      {
        "name": "ERYONE Silk PLA Filament for 3D Printer",
        "description": "ERYONE Silk PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - White",
        "price": "$39.52",
        "cutoff": "$48.75",
        "off": "(19% off)",
        "ratings": "234",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-17/ERYONE-Silk-PLA-Filament-for-3D-Printer-1-75mm-496628-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"7",
        "sale":"yes",
        "shipping":"no",
        "country":"Germany"
      },
      {
        "name": "ERYONE Silk PLA Filament for 3D Printer",
        "description": "ERYONE Silk PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - Pink",
        "price": "$39.52",
        "cutoff": "$48.75",
        "off": "(19% off)",
        "ratings": "222",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-17/ERYONE-Silk-PLA-Filament-for-3D-Printer-1-75mm-496633-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"15",
        "sale":"no",
        "shipping":"yes",
        "country":"Spain"
      },
      {
        "name": "ERYONE PETG Filament for 3D Printer",
        "description": "ERYONE PETG Filament for 3D Printer 1.75mm Tolerance 0.03mm 1KG(2.2LBS)/Spool - White",
        "price": "$35.57",
        "cutoff": "$40.84",
        "off": "(13% off)",
        "ratings": "65",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-21/ERYONE-PETG-Filament-for-3D-Printer-1-75mm-496793-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"30",
        "sale":"yes",
        "shipping":"no",
        "country":"United_States"
      },
      {
        "name": "ERYONE PETG Filament for 3D Printer",
        "description": "ERYONE PETG Filament for 3D Printer 1.75mm Tolerance 0.03mm 1KG(2.2LBS)/Spool - Orange",
        "price": "$35.57",
        "cutoff": "$40.84",
        "off": "(13% off)",
        "ratings": "234",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-21/ERYONE-PETG-Filament-for-3D-Printer-1-75mm-496798-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"7",
        "sale":"no",
        "shipping":"yes",
        "country":"United_Kingdom"
      },
      {
        "name": "ERYONE PETG Filament for 3D Printer",
        "description": "ERYONE PETG Filament for 3D Printer 1.75mm Tolerance 0.03mm 1KG(2.2LBS)/Spool - Black",
        "price": "$35.57",
        "cutoff": "$40.84",
        "off": "(13% off)",
        "ratings": "133",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-21/ERYONE-PETG-Filament-for-3D-Printer-1-75mm-496803-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"15",
        "sale":"yes",
        "shipping":"no",
        "country":"Netherland"
      },
      {
        "name": "ERYONE PETG Filament for 3D Printer",
        "description": "ERYONE PETG Filament for 3D Printer 1.75mm Tolerance 0.03mm 1KG(2.2LBS)/Spool - Red",
        "price": "$35.57",
        "cutoff": "$40.84",
        "off": "(13% off)",
        "ratings": "44",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-21/ERYONE-PETG-Filament-for-3D-Printer-1-75mm-496808-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"30",
        "sale":"no",
        "shipping":"yes",
        "country":"China"
      },
      {
        "name": "ERYONE PETG Filament for 3D Printer",
        "description": "ERYONE PETG Filament for 3D Printer 1.75mm Tolerance 0.03mm 1KG(2.2LBS)/Spool - Yellow",
        "price": "$35.57",
        "cutoff": "$40.84",
        "off": "(13% off)",
        "ratings": "56",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-21/ERYONE-PETG-Filament-for-3D-Printer-1-75mm-496813-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"7",
        "sale":"yes",
        "shipping":"no",
        "country":"Europe"
      },
      {
        "name": "ERYONE PETG Filament for 3D Printer",
        "description": "ERYONE PETG Filament for 3D Printer 1.75mm Tolerance 0.03mm 1KG(2.2LBS)/Spool- Grey",
        "price": "$35.57",
        "cutoff": "CA$40.84",
        "off": "(13% off)",
        "ratings": "65",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-21/ERYONE-PETG-Filament-for-3D-Printer-1-75mm-496818-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"15",
        "sale":"no",
        "shipping":"yes",
        "country":"Poland"
      },
      {
        "name": "ERYONE PETG Filament for 3D Printer",
        "description": "ERYONE PETG Filament for 3D Printer 1.75mmTolerance 0.03mm 1KG(2.2LBS)/Spool - Blue",
        "price": "$35.57",
        "cutoff": "$40.84",
        "off": "(13% off)",
        "ratings": "87",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-21/ERYONE-PETG-Filament-for-3D-Printer-1-75mm-496823-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"30",
        "sale":"yes",
        "shipping":"no",
        "country":"Germany"
      },
      {
        "name": "ERYONE PETG Filament for 3D Printer",
        "description": "ERYONE PETG Filament for 3D Printer 1.75mm Tolerance 0.03mm 1KG(2.2LBS)/Spool - Transparent Red",
        "price": "$35.57",
        "cutoff": "$40.84",
        "off": "(13% off)",
        "ratings": "212",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-21/ERYONE-PETG-Filament-for-3D-Printer-1-75mm-496828-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"7",
        "sale":"no",
        "shipping":"yes",
        "country":"Spain"
      },
      {
        "name": "ERYONE PETG Filament for 3D Printer",
        "description": "ERYONE PETG Filament for 3D Printer 1.75mm Tolerance 0.03mm 1KG(2.2LBS)/Spool - Transparent Blue",
        "price": "$35.57",
        "cutoff": "$40.84",
        "off": "(13% off)",
        "ratings": "156",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-21/ERYONE-PETG-Filament-for-3D-Printer-1-75mm-496833-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"15",
        "sale":"yes",
        "shipping":"no",
        "country":"United_States"
      },
      {
        "name": "ERYONE PLA Filament for 3D Printer",
        "description": "ERYONE PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - White",
        "price": "$35.57",
        "cutoff": "$40.84",
        "off": "(13% off)",
        "ratings": "134",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-23/ERYONE-PLA-Filament-for-3D-Printer-1-75mm-496852-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"30",
        "sale":"no",
        "shipping":"yes",
        "country":"United_Kingdom"
      },
      {
        "name": "Tronsmart Element Mega SoundPulse™ Bluetooth",
        "description": "Tronsmart Element Mega SoundPulse™ Bluetooth 5.0 Speaker with Powerful 40W Max Output 3D Digital Sound TWS Intuitive Touch Control - Black",
        "price": "$57.97",
        "cutoff": "$88.28",
        "off": "(34% off)",
        "ratings": "328",
        "imgURL": "https://img.gkbcdn.com/p/2019-01-31/tronsmart-element-mega-bluetooth-speaker-black-1571991584812._w280_.jpg",
        "wishlist": "1289",
        "arrived":"7",
        "sale":"yes",
        "shipping":"no",
        "country":"Netherland"
      },
      {
        "name": "MX3-L-M Backlight & Voice Input 6-Axis Gyro ",
        "description": "MX3-L-M Backlight & Voice Input 6-Axis Gyro 2.4GHz Wireless Air Mouse QWERTY Keyboard with IR Learning Remote Control for Android/Windows/Linux Systems - Black",
        "price": "$18.44",
        "ratings": "11",
        "imgURL": "https://img.gkbcdn.com/p/2017-11-25/mx3-l-m-backlight-voice-input-2-4ghz-wireless-air-mouse-1571989128244._w280_.jpg",
        "wishlist": "231",
        "arrived":"15",
        "sale":"no",
        "shipping":"yes",
        "country":"China"
      },
      {
        "name": "Tronsmart Force SoundPulse™ 40W Bluetooth",
        "description": "Tronsmart Force SoundPulse™ 40W Bluetooth 5.0 Speaker IPX7 Water Resistant Siri TWS & NFC 15 Hours Playtime",
        "price": "$75.10",
        "cutoff": "$92.23",
        "off": "(19% off)",
        "ratings": "219",
        "imgURL": "https://img.gkbcdn.com/p/2019-01-31/tronsmart-element-force-portable-bluetooth-speaker-1571993707403._w280_.jpg",
        "wishlist": "661",
        "arrived":"30",
        "sale":"yes",
        "shipping":"no",
        "country":"Europe"
      },
      {
        "name": "Tronsmart Element T6 Plus Portable Bluetooth",
        "description": "Tronsmart Element T6 Plus Portable Bluetooth 5.0 Speaker with 40W Max Output, Deep Bass, IPX6 Waterproof, TWS - Black",
        "price": "$79.05",
        "cutoff": "$105.41",
        "off": "(25% off)",
        "ratings": "211",
        "imgURL": "https://img.gkbcdn.com/p/2019-03-18/tronsmart-element-t6-plus-bluetooth-speaker-black-1574132869322._w280_.jpg",
        "wishlist": "631",
        "arrived":"7",
        "sale":"no",
        "shipping":"yes",
        "country":"Poland"
      },
      {
        "name": "Xiaomi WiFi Amplifier Pro 2X2 External Antenna",
        "description": "Xiaomi WiFi Amplifier Pro 2X2 External Antenna 300Mbps Support 64 Devices Simultaneous Link - Black",
        "price": "$26.34",
        "cutoff": "$35.57",
        "off": "(26% off)",
        "ratings": "120",
        "imgURL": "https://img.gkbcdn.com/p/2017-07-26/xiaomi-wifi-amplifier-pro-black-1574132393616._w280_.jpg",
        "wishlist": "888",
        "arrived":"15",
        "sale":"yes",
        "shipping":"no",
        "country":"Germany"
      },
      {
        "name": "Apods i500 Bluetooth 5.0 Pop-up Window TWS",
        "description": "Apods i500 Bluetooth 5.0 Pop-up Window TWS Earbuds Independent Usage Wireless Charging IPX5 - White",
        "price": "$19.23",
        "cutoff": "$32.93",
        "off": "(42% off)",
        "ratings": "35",
        "imgURL": "https://img.gkbcdn.com/p/2019-11-30/tws-i500-earphones-20191130100234539._w280_.jpg",
        "wishlist": "325",
        "arrived":"30",
        "sale":"no",
        "shipping":"yes",
        "country":"Spain"
      },
      {
        "name": "Tronsmart Onyx Ace Pro True Wireless Earbuds",
        "description": "Tronsmart Onyx Ace Pro True Wireless Earbuds TWS Earphones, Qualcomm QCC3040, Qualcomm aptX Adaptive, 27H Playtime, IPX5, One Key Recovery, White",
        "price": "$39.52",
        "cutoff": "$52.70",
        "off": "(25% off)",
        "ratings": "125",
        "imgURL": "https://img.gkbcdn.com/p/2020-03-18/Tronsmart-Onyx-Ace-Bluetooth-5-0-TWS-Earphones-White-899355-._w280_.jpg",
        "wishlist": "426",
        "arrived":"7",
        "sale":"yes",
        "shipping":"no",
        "country":"United_States"
      },
      {
        "name": "Tronsmart Force/Mega/T6/T6 Plus/T6 Plus Upgraded",
        "description": "Tronsmart Force/Mega/T6/T6 Plus/T6 Plus Upgraded Carrying Case Portable Travel Bag Protective Case",
        "price": "$15.80",
        "ratings": "119",
        "imgURL": "https://img.gkbcdn.com/p/2019-03-16/tronsmart-force-mega-t6-t6-plus-speaker-carry-case-1571991604256._w280_.jpg",
        "wishlist": "105",
        "arrived":"15",
        "sale":"no",
        "shipping":"yes",
        "country":"United_Kingdom"
      },
      {
        "name": "Mifo O7 Bluetooth 5.0 Qualcomm QCC3020 TWS Earphones",
        "description": "Mifo O7 Bluetooth 5.0 Qualcomm QCC3020 TWS Earphones Carbon Nanotube Dynamic Drivers Independent Usage IPX7 AAC/SBC/aptX Compatible with Alexa Siri 7 Hours Playtime - Black",
        "price": "$131.77",
        "cutoff": "$210.83",
        "off": "(38% off)",
        "ratings": "114",
        "imgURL": "https://img.gkbcdn.com/p/2019-11-15/mifo-o7-bluetooth-5-0-tws-qualcomm-qcc3020-earphones-black-1574132882676._w280_.jpg",
        "wishlist": "75",
        "arrived":"30",
        "sale":"yes",
        "shipping":"no",
        "country":"Netherland"
      },
      {
        "name": "Tronsmart T2 Plus 20W Bluetooth 5.0 Speaker",
        "description": "Tronsmart T2 Plus 20W Bluetooth 5.0 Speaker 24H Playtime NFC IPX7 Waterproof Soundbar with TWS,Siri,Micro SD",
        "price": "$43.47",
        "cutoff": "$55.33",
        "off": "(21% off)",
        "ratings": "89",
        "imgURL": "https://img.gkbcdn.com/p/2019-08-27/tronsmart-t2-plus-20w--bluetooth-5-0-speaker-tws-1571994588089._w280_.jpg",
        "wishlist": "275",
        "arrived":"7",
        "sale":"no",
        "shipping":"yes",
        "country":"China"
      }
    



]


localStorage.setItem("BestSeller",JSON.stringify(BestSeller))

console.log(NewProducts.length)